"""Process-wide knowledge-card generation runtime (KB-02 → ASM-01).

Analogous in lifecycle quality to the media runtime
(:mod:`deeptutor.services.media.runtime`): discovers learning roots, recovers
deterministic nonterminal attempts on startup, periodically selects queued
runnable generation attempts and calls
:meth:`KnowledgeCardGenerationWorker.run_attempt` with bounded concurrency /
single-flight behaviour, and starts/stops from the FastAPI lifespan.

The provider executor (the production :class:`FrozenModelDraftExecutor`) is
resolved *lazily per attempt* from that attempt's frozen evaluator snapshot and
the current server-side catalog/credentials, so:

* a process with no configured provider never opens HTTP clients at startup;
* each attempt is generated by the exact frozen profile/model/protocol — never
  silent fallback, never the teaching model;
* roots created after startup are discovered on the next pass.

A manager constructed with ``roots=[...]`` never scans the global layout
(offline determinism for tests); the process singleton uses production
discovery and the real executor factory.
"""

from __future__ import annotations

import asyncio
import logging
from pathlib import Path
import time
from typing import Any, Awaitable, Callable

from deeptutor.learning.knowledge_cards.store import find_card
from deeptutor.learning.knowledge_cards.worker import (
    DraftExecutor,
    KnowledgeCardGenerationWorker,
)
from deeptutor.learning.models import GenerationAttemptStatus
from deeptutor.learning.storage import LearningStore

logger = logging.getLogger(__name__)

#: Injectable sleep so offline tests advance the loop deterministically.
SleepFn = Callable[[float], Awaitable[None]]
#: Builds the DraftExecutor (provider adapter) for one generation attempt.
#: ``None`` means "no provider configured" — the worker then fails attempts with
#: a stable ``no_executor`` state instead of guessing a provider.
ExecutorFactory = Callable[[Any], DraftExecutor]


def default_learning_root() -> Path:
    """The default (admin) learning root under the persistent data layout."""
    from deeptutor.services.path_service import get_path_service

    return Path(get_path_service().get_workspace_dir()) / "learning"


def discover_learning_roots() -> list[Path]:
    """Every learning root that exists under the persistent data layout.

    The default root is always included (created lazily by the store); per-user
    roots under ``data/users/<uid>/user/workspace/learning`` are included only
    when they already exist, so a fresh deployment does not fabricate empty user
    trees. The ``user`` component matches the real :class:`PathService` layout
    (``PathService(workspace_root=data/users/<uid>)`` sets ``_user_data_dir`` to
    ``workspace_root / "user"`` and ``get_workspace_dir()`` appends
    ``workspace``), not a guessed sibling path.
    """
    roots = [Path(default_learning_root())]
    try:
        from deeptutor.multi_user.paths import USERS_ROOT

        if USERS_ROOT.is_dir():
            for user_dir in sorted(USERS_ROOT.iterdir()):
                candidate = user_dir / "user" / "workspace" / "learning"
                if candidate.is_dir():
                    roots.append(candidate)
    except Exception:  # noqa: BLE001 - optional discovery must never fail startup
        logger.debug("could not discover per-user learning roots", exc_info=True)
    return roots


def _default_executor_factory(attempt: Any) -> DraftExecutor:
    from deeptutor.learning.knowledge_cards.executor import FrozenModelDraftExecutor

    return FrozenModelDraftExecutor(attempt.frozen_model_snapshot)


class KnowledgeCardRuntime:
    """Advances every learning root's queued generation attempts."""

    def __init__(
        self,
        *,
        roots: list[Path] | None = None,
        executor_factory: ExecutorFactory | None = None,
        sleep: SleepFn | None = None,
        now: Callable[[], float] | None = None,
        concurrency: int = 1,
    ) -> None:
        self._explicit_roots = roots is not None
        self._roots = [Path(p) for p in (roots if roots is not None else discover_learning_roots())]
        self._root_keys = {self._root_key(p) for p in self._roots}
        self._executor_factory = executor_factory
        self._sleep = sleep or self._asyncio_sleep
        self._now = now or time.time
        self._concurrency = max(1, int(concurrency))
        self._workers: dict[str, KnowledgeCardGenerationWorker] = {}
        #: Per-attempt executors so aclose can release every lazily-built one.
        self._executors: dict[str, DraftExecutor] = {}
        self._inflight: dict[str, str] = {}
        self._stop_event: asyncio.Event | None = None
        self._task: asyncio.Task[None] | None = None

    @staticmethod
    async def _asyncio_sleep(seconds: float) -> None:
        await asyncio.sleep(seconds)

    @property
    def roots(self) -> list[Path]:
        return list(self._roots)

    @staticmethod
    def _root_key(root: Path) -> str:
        return str(Path(root).resolve())

    def _worker_for(self, root: Path) -> KnowledgeCardGenerationWorker:
        key = self._root_key(root)
        worker = self._workers.get(key)
        if worker is None:
            worker = KnowledgeCardGenerationWorker(store=LearningStore(root=root), now=self._now)
            self._workers[key] = worker
        return worker

    def _refresh_roots(self) -> None:
        """Re-discover per-user learning roots created since startup.

        Only managers built *without* explicit ``roots=[...]`` refresh; managers
        given explicit roots never scan unrelated global roots (offline
        determinism). Existing workers are keyed by resolved root and preserved.
        """
        if self._explicit_roots:
            return
        for root in discover_learning_roots():
            key = self._root_key(root)
            if key in self._root_keys:
                continue
            self._roots.append(Path(root))
            self._root_keys.add(key)
            logger.info("knowledge-card runtime: discovered new learning root %s", root)

    # ── recovery ─────────────────────────────────────────────────────────────

    def recover(self) -> list[dict[str, str]]:
        """Apply the deterministic restart rules to every root (§7.9.1)."""
        outcomes: list[dict[str, str]] = []
        for root in self._roots:
            try:
                outcomes.extend(self._worker_for(root).recover())
            except Exception as exc:  # noqa: BLE001 - one root must never stop startup
                logger.warning(
                    "knowledge-card recovery failed for %s (%s)", root, type(exc).__name__
                )
        return outcomes

    # ── selection / execution ────────────────────────────────────────────────

    def _next_runnable(self, worker: KnowledgeCardGenerationWorker) -> tuple[str, Any] | None:
        """A ``(book_id, attempt)`` for the first queued runnable attempt."""
        for book_id in worker.store.list_all():
            progress = worker.store.load(book_id)
            if progress is None:
                continue
            for attempt in progress.knowledge_card_generation_attempts:
                if attempt.status != GenerationAttemptStatus.QUEUED:
                    continue
                card = find_card(progress, attempt.card_id)
                if card is None:
                    continue
                runnable, _ = worker._card_is_runnable(progress, card, attempt)
                if runnable:
                    return book_id, attempt
        return None

    def _select(self) -> list[tuple[Path, str, Any]]:
        """Pick up to ``concurrency`` runnable attempts, one per root (single-flight)."""
        selected: list[tuple[Path, str, Any]] = []
        for root in self._roots:
            key = self._root_key(root)
            if key in self._inflight and self._inflight[key]:
                continue
            worker = self._worker_for(root)
            found = self._next_runnable(worker)
            if found is None:
                continue
            book_id, attempt = found
            self._inflight[key] = attempt.id
            selected.append((root, book_id, attempt))
            if len(selected) >= self._concurrency:
                break
        return selected

    async def run_once(self) -> int:
        """Advance up to ``concurrency`` queued attempts; returns the count.

        Selected attempts (at most one per root) run *concurrently* with a
        bounded task set sized by ``concurrency`` — a configured concurrency of
        N really produces up to N overlapping provider calls, never N sequential
        awaits. Each task binds the correct per-attempt executor to its own
        per-root worker (roots are single-flight, so no two tasks ever share a
        worker's executor slot) and clears its ``_inflight`` marker
        deterministically in every outcome.
        """
        self._refresh_roots()
        selected = self._select()
        if not selected:
            return 0
        semaphore = asyncio.Semaphore(self._concurrency)

        async def _advance(root: Path, book_id: str, attempt: Any) -> None:
            key = self._root_key(root)
            try:
                async with semaphore:
                    self._ensure_executor(attempt)
                    worker = self._worker_for(root)
                    worker.set_executor(self._executors.get(attempt.id))
                    await worker.run_attempt(book_id, attempt.id)
            except Exception as exc:  # noqa: BLE001 - one attempt must never stop the loop
                logger.warning(
                    "knowledge-card generation attempt %s failed to advance (%s)",
                    attempt.id,
                    type(exc).__name__,
                )
            finally:
                self._inflight[key] = ""

        await asyncio.gather(
            *(_advance(root, book_id, attempt) for root, book_id, attempt in selected)
        )
        return len(selected)

    def _ensure_executor(self, attempt: Any) -> None:
        """Lazily build the attempt's production DraftExecutor (once per attempt)."""
        if attempt.id in self._executors:
            return
        if self._executor_factory is None:
            return
        try:
            self._executors[attempt.id] = self._executor_factory(attempt)
        except Exception as exc:  # noqa: BLE001 - no executor must not break the loop
            logger.warning(
                "knowledge-card executor resolution failed for %s (%s)",
                attempt.id,
                type(exc).__name__,
            )

    async def run_forever(self, *, interval: float = 1.0) -> None:
        """Advance queued attempts until :meth:`stop` is called."""
        while self._stop_event is None or not self._stop_event.is_set():
            await self.run_once()
            await self._sleep(interval)

    # ── lifecycle ────────────────────────────────────────────────────────────

    def start(self, *, interval: float = 1.0) -> asyncio.Task[None]:
        """Start the background scheduler task (idempotent)."""
        if self._task is not None and not self._task.done():
            return self._task
        self._stop_event = asyncio.Event()
        self._task = asyncio.create_task(self.run_forever(interval=interval))
        return self._task

    async def stop(self) -> None:
        """Stop the background loop and release every executor (bounded).

        A provider call may be mid-flight at shutdown; we give the loop a short
        grace period then cancel it — the worker's deterministic restart
        recovery reconciles an interrupted running attempt on the next start
        (§7.9.1), so a hard stop is safe and never blocks the process.
        """
        if self._stop_event is not None:
            self._stop_event.set()
        task = self._task
        self._task = None
        if task is not None and not task.done():
            try:
                await asyncio.wait_for(asyncio.shield(task), timeout=5.0)
            except asyncio.TimeoutError:
                task.cancel()
                try:
                    await task
                except (asyncio.CancelledError, Exception):  # noqa: BLE001
                    logger.debug("knowledge-card runtime task cancelled during shutdown")
        await self.aclose()

    async def aclose(self) -> None:
        """Best-effort close of every lazily-built provider executor."""
        for key, executor in list(self._executors.items()):
            closer = getattr(executor, "aclose", None)
            if closer is not None:
                try:
                    await closer()
                except Exception:  # noqa: BLE001 - best-effort shutdown
                    logger.debug("knowledge-card executor %s close failed", key, exc_info=True)
        self._executors.clear()


#: Process-wide singleton, wired into the FastAPI lifespan by
#: ``deeptutor.api.main``.
_runtime: KnowledgeCardRuntime | None = None


def get_knowledge_card_runtime() -> KnowledgeCardRuntime:
    """The process-wide knowledge-card runtime (created on first access).

    Production binds the real :class:`FrozenModelDraftExecutor` through
    :func:`_default_executor_factory`; ``executor_factory=None`` (the
    constructor default) is the explicit offline path that disables executors.
    """
    global _runtime
    if _runtime is None:
        _runtime = KnowledgeCardRuntime(executor_factory=_default_executor_factory)
    return _runtime


def reset_knowledge_card_runtime() -> None:
    """Drop the singleton (used by offline lifecycle tests)."""
    global _runtime
    _runtime = None


__all__ = [
    "ExecutorFactory",
    "KnowledgeCardRuntime",
    "default_learning_root",
    "discover_learning_roots",
    "get_knowledge_card_runtime",
    "reset_knowledge_card_runtime",
]
